# Site wide configuration

title: Buseung
description: "buseung blog"
logo: buseung.jpeg # 120x120 px default image used for Twitter summary card
teaser: winter.jpg # 400x250 px default teaser image used in image archive grid
#locale:
url: http://kbs0327.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Buseung Kim
  email: buseung.kim@nhnent.com
  facebook: mug0327@hanmail.net
 # google:
 #   ad-client: 
 #   ad-slot: 
 # bio: 
  avatar: buseung.jpeg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
